# Generated by Django 6.1.1 on 2026-09-29 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="operation_suivante",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.operation",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="operations",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.operation",
            ),
        ),
    ]
