# Generated by Django 6.1.1 on 2026-09-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0003_alter_operation_operation_suivante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transport",
            name="nom",
            field=models.CharField(default="transport", max_length=100),
        ),
    ]
