# Generated by Django 6.1.1 on 2026-09-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0004_transport_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lieu",
            name="quantite_machine",
            field=models.ManyToManyField(
                blank=True, null=True, to="high_level.quantitemachine"
            ),
        ),
    ]
